plugins:
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end
Layout/EndAlignment:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods:
    - config
    - configure
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Enabled: true
  Max: 25
Metrics/ClassLength:
  Enabled: true
  Max: 150
Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Enabled: true
  Max: 25

Style/BlockDelimiters:
  AllowedMethods:
    - lambda
    - proc
  Enabled: true
Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: false